# Generated by Django 4.2.9 on 2024-05-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("P", "Participants"),
                    ("C", "Coordinator"),
                    ("V", "Volunteer"),
                    ("A", "Admin"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
