# Generated by Django 4.2.9 on 2024-05-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_points_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
